### ISSUE TITLE
글쓰기가 안됩니다.

### ISSUE THREAD

**Issue by wjdgml1026** [song9446/dcinside-python3-api#2]
7월 27일부터 글쓰기가 안먹혀요.

<script>alert('잠시후 다시 이용 바랍니다.');
			location.href='https://m.dcinside.com/write/주소';
			</script>

계속해서 이렇게 response가 오는데 디시쪽에서 뭔가를 바꾼건가요?

**Comment by song9446** [comment]
그런거같아요.. 요즘 도배가 너무 심하다보니까 디시측에서 뭔가를 또 바꿨나봐요..

한번 확인해볼게요
________________________________
보낸 사람: wjdgml1026 <notifications@github.com>
보낸 날짜: 2019년 7월 29일 월요일 오후 1:48
받는 사람: song9446/dcinside-python3-api <dcinside-python3-api@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
제목: [song9446/dcinside-python3-api] 글쓰기가 안됩니다. (#2)


7월 27일부터 글쓰기가 안먹혀요.. 잠시후 다시 작성해주세요. 라고 response가 오는데 디시쪽에서 뭔가를 바꾼건가요?

**Comment by wjdgml1026** [comment]
혹시 수정됬을까요??

**Comment by song9446** [comment]
#3
