### ISSUE TITLE
API 동작 안되는 이슈

### ISSUE THREAD

**Issue by deerFried** [song9446/dcinside-python3-api#3]
댓글쓰기 API로만 확인해본거라 다른 API에서는 확실하지 않을 수도 있습니다.

일단 ajax access를 호출할 때 x-csrf-token 및 referer, cookie가 필수적으로 header에 들어가도록 변경된걸로 확인됩니다. cookie의 경우에는 _ga 값만 있어도 충분한 것으로 보입니다. 실제로 해당 값들을 적절하게 세팅하지 않은 상태로 api request를 보내면 3ebxxxxx 이런식의 키가 내려오는 반면 해당 값들을 세팅하고 request를 보내면 2ebxxxxx 같은 형식의 키가 내려옵니다. 그리고 현재 dc에서 사용중인 key는 2ebxxxx 같은 형태의 키값입니다.

comment_write API도 이와 동일한 이슈로 판단되어 cookie값과 나머지 값들을 세팅하고 request 해본 결과 정상적으로 API가 동작하는 것을 확인할 수 있었습니다. bugfix에 참고 부탁드리며 시간나면 PR올려보도록 하겠습니다.

**Comment by tolluset** [comment]
변경한 코드 부분이라도 공유해주실 수 있나염 ㅇㅁㅇ...

**Comment by song9446** [comment]
제보감사합니다 반영하였습니다
