### ISSUE TITLE
에러 질문이 있습니다. 

### ISSUE THREAD

**Issue by arnoldchung** [song9446/dcinside-python3-api#9]
설치 후 예문을 돌려보았습니다.

# 프로그래밍 갤러리 글 무한 크롤링
api = dc_api.API()
async for metadoc in api.board(board_id="programming"):
    print(metadoc.title) 

  File "<stdin>", line 1
SyntaxError: 'async for' outside async function 라고 뜨는데 어떻게 해결해야하나요?
감사합니다.

**Comment by eunchuldev** [comment]
리드미 업데이트했어요.
